Github CI: Deactivated pipeline

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,60 +1,60 @@
-name: Build and Deploy Project
+# name: Build and Deploy Project
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-env:
-  GODOT_VERSION: 4.3
-  #EXPORT_NAME: LD56
-  PROJECT_PATH: game/ld56_godot
+# env:
+#   GODOT_VERSION: 4.3
+#   #EXPORT_NAME: LD56
+#   PROJECT_PATH: game/ld56_godot
 
-jobs:
-  export_game:
-    runs-on: ubuntu-latest
-    name: Web Export
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-        with:
-          lfs: true
+# jobs:
+#   export_game:
+#     runs-on: ubuntu-latest
+#     name: Web Export
+#     steps:
+#       - name: Checkout
+#         uses: actions/checkout@v4
+#         with:
+#           lfs: true
 
-      - name: Download Godot
-        run: |
-          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O godot.zip
-          unzip godot.zip -d ~/godot
-          chmod +x ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
+#       - name: Download Godot
+#         run: |
+#           wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux.x86_64.zip -O godot.zip
+#           unzip godot.zip -d ~/godot
+#           chmod +x ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64
 
-      - name: Download Godot export templates
-        run: |
-          wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz -O ${GODOT_VERSION}.stable.tpz
-          mkdir -p ~/.local/share/godot/export_templates
-          unzip -o ${GODOT_VERSION}.stable.tpz -d ~/.local/share/godot/export_templates
-          # Rename the extracted folder to the expected version name
-          mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable || { echo "Error: Could not rename templates folder."; exit 1; }
+#       - name: Download Godot export templates
+#         run: |
+#           wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_export_templates.tpz -O ${GODOT_VERSION}.stable.tpz
+#           mkdir -p ~/.local/share/godot/export_templates
+#           unzip -o ${GODOT_VERSION}.stable.tpz -d ~/.local/share/godot/export_templates
+#           # Rename the extracted folder to the expected version name
+#           mv ~/.local/share/godot/export_templates/templates ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable || { echo "Error: Could not rename templates folder."; exit 1; }
 
-      - name: Prepare output directory
-        run: |
-          mkdir -p ./build/web
+#       - name: Prepare output directory
+#         run: |
+#           mkdir -p ./build/web
 
-      - name: Export game
-        run: |
-          ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --path ${PROJECT_PATH} --export-release "web" ../build/web/index.html
-        #env:
-          #GITHUB_TOKEN: ${{ secrets.GH_KEY }}
+#       - name: Export game
+#         run: |
+#           ~/godot/Godot_v${GODOT_VERSION}-stable_linux.x86_64 --headless --path ${PROJECT_PATH} --export-release "web" ../build/web/index.html
+#         #env:
+#           #GITHUB_TOKEN: ${{ secrets.GH_KEY }}
 
-      - name: Upload Artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: web
-          path: build/web
+#       - name: Upload Artifact
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: web
+#           path: build/web
 
-      # - name: Upload to itch.io
-      #   uses: manleydev/butler-publish-itchio-action@master
-      #   env:
-      #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
-      #     CHANNEL: web
-      #     ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
-      #     ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
-      #     PACKAGE: build/web
+#       # - name: Upload to itch.io
+#       #   uses: manleydev/butler-publish-itchio-action@master
+#       #   env:
+#       #     BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
+#       #     CHANNEL: web
+#       #     ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
+#       #     ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
+#       #     PACKAGE: build/web
